# Generated by Django 5.1.7 on 2025-04-25 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_execution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='execution',
            options={'verbose_name_plural': 'Исполнение'},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name_plural': 'Задача'},
        ),
    ]
